[package]
name = "log4rs"
version = "0.3.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "A highly configurable multi-output logging implementation for the `log` facade"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/log4rs"
documentation = "https://sfackler.github.io/log4rs/doc/v0.3.3/log4rs"

[features]
yaml = ["serde_yaml"]
json = ["serde_json"]

[dependencies]
time = "0.1"
log = "0.3"
nom = "1.0.1"
typemap = "0.3"
serde = "0.7"
serde-value = "0.1"
serde_yaml = { version = "0.2", optional = true }
serde_json = { version = "0.7", optional = true }
toml = { version = "0.1.28", optional = true, default_features = false, features = ["serde"] }
