[package]
name = "log4rs"
version = "0.4.8"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "A highly configurable multi-output logging implementation for the `log` facade"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/log4rs"
documentation = "https://sfackler.github.io/log4rs/doc/v0.4.8/log4rs"

[features]
yaml = ["serde_yaml"]
json = ["serde_json"]
gzip = ["flate2"]

[dependencies]
antidote = "1.0"
chrono = "0.2"
crossbeam = "0.2.9"
flate2 = { version = "0.2", optional = true }
humantime = "1.0"
libc = "0.2"
log = "0.3"
serde = "0.8"
serde-value = "0.3"
typemap = "0.3"
serde_json = { version = "0.8", optional = true }
serde_yaml = { version = "0.4", optional = true }
toml = { version = "0.2", optional = true, default_features = false, features = ["serde"] }

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2"
winapi = "0.2"

[dev-dependencies]
tempdir = "0.3"
